import Foundation
@testable import MeetingTranscriber

// MARK: - Shared Mock Classes

/// Mock recorder that returns a pre-prepared fixture WAV as the recording result.
@MainActor
class MockRecorder: RecordingProvider {
    var mixPath: URL?
    var appPath: URL?
    var micPath: URL?
    var startCalled = false
    var stopCalled = false

    func start(appPID _: pid_t, noMic _: Bool, micDeviceUID _: String?) {
        startCalled = true
    }

    func stop() async throws -> RecordingResult {
        stopCalled = true
        guard let mix = mixPath else {
            throw RecorderError.noAudioData
        }
        return RecordingResult(
            mixPath: mix,
            appPath: appPath,
            micPath: micPath,
            micDelay: 0,
            recordingStart: ProcessInfo.processInfo.systemUptime,
        )
    }
}

/// Mock diarization that returns pre-set segments.
class MockDiarization: DiarizationProvider {
    var isAvailable: Bool = true
    var runCalled = false
    var resultToReturn: DiarizationResult?

    // swiftlint:disable:next async_without_await
    func run(audioPath _: URL, numSpeakers _: Int?, meetingTitle _: String) async -> DiarizationResult {
        runCalled = true
        if let result = resultToReturn {
            return result
        }
        return DiarizationResult(
            segments: [
                .init(start: 0, end: 5, speaker: "SPEAKER_00"),
                .init(start: 5, end: 10, speaker: "SPEAKER_01"),
            ],
            speakingTimes: ["SPEAKER_00": 5.0, "SPEAKER_01": 5.0],
            autoNames: [:],
            embeddings: nil,
        )
    }
}

/// Mock protocol generator that captures the transcript instead of calling Claude CLI.
class MockProtocolGen: ProtocolGenerating {
    var generateCalled = false
    var capturedTranscript: String?
    var capturedTitle: String?
    // swiftlint:disable:next discouraged_optional_boolean
    var capturedDiarized: Bool?

    // swiftlint:disable:next async_without_await
    func generate(transcript: String, title: String, diarized: Bool) async -> String {
        generateCalled = true
        capturedTranscript = transcript
        capturedTitle = title
        capturedDiarized = diarized
        return """
        # Meeting Protocol - \(title)
        **Date:** 2026-03-06

        ---

        ## Summary
        Test protocol generated by mock.
        """
    }
}
