import Foundation
@testable import MeetingTranscriber
import WhisperKit

// MARK: - WatchLoop / AppState Helpers

/// Returns a MeetingDetector with no patterns — never matches any window.
func makeSilentDetector() -> MeetingDetector {
    MeetingDetector(patterns: [])
}

/// Creates a WatchLoop backed by a MockRecorder and a silent detector.
/// Assign the returned loop to `appState.watchLoop` in tests that need
/// an active loop without calling toggleWatching() (which requires Permissions).
@MainActor
func makeTestWatchLoop(
    pipelineQueue: PipelineQueue? = nil,
) -> (WatchLoop, MockRecorder) {
    let recorder = MockRecorder()
    recorder.mixPath = URL(fileURLWithPath: "/tmp/test_mix.wav")
    let loop = WatchLoop(
        detector: makeSilentDetector(),
        recorderFactory: { recorder },
        pipelineQueue: pipelineQueue,
        pollInterval: 0.05,
        endGracePeriod: 0.1,
    )
    loop.permissionChecker = {
        HealthCheckResult(screenRecording: .healthy, microphone: .healthy)
    }
    return (loop, recorder)
}

// MARK: - AppNotifying spy

/// Records all notify() calls for assertions.
final class RecordingNotifier: AppNotifying {
    private(set) var calls: [(title: String, body: String)] = []

    func notify(title: String, body: String) {
        calls.append((title: title, body: body))
    }
}

// MARK: - Shared Mock Classes

/// Mock recorder that returns a pre-prepared fixture WAV as the recording result.
@MainActor
class MockRecorder: RecordingProvider {
    var mixPath: URL?
    var appPath: URL?
    var micPath: URL?
    var startCalled = false
    var stopCalled = false

    func start(appPID _: pid_t, noMic _: Bool, micDeviceUID _: String?) {
        startCalled = true
    }

    func stop() throws -> RecordingResult {
        stopCalled = true
        guard let mix = mixPath else {
            throw RecorderError.noAudioData
        }
        return RecordingResult(
            mixPath: mix,
            appPath: appPath,
            micPath: micPath,
            micDelay: 0,
            recordingStart: ProcessInfo.processInfo.systemUptime,
        )
    }
}

/// Mock diarization that returns pre-set segments.
class MockDiarization: DiarizationProvider {
    var isAvailable: Bool = true
    var runCount = 0
    var shouldThrow = false
    var resultToReturn: DiarizationResult?

    func run(audioPath _: URL, numSpeakers _: Int?, meetingTitle _: String) -> DiarizationResult {
        runCount += 1
        if shouldThrow {
            // Return empty result to simulate failure path
            return DiarizationResult(segments: [], speakingTimes: [:], autoNames: [:], embeddings: nil)
        }
        if let result = resultToReturn {
            return result
        }
        return DiarizationResult(
            segments: [
                .init(start: 0, end: 5, speaker: "SPEAKER_00"),
                .init(start: 5, end: 10, speaker: "SPEAKER_01"),
            ],
            speakingTimes: ["SPEAKER_00": 5.0, "SPEAKER_01": 5.0],
            autoNames: [:],
            embeddings: nil,
        )
    }
}

/// Mock protocol generator that captures the transcript instead of calling Claude CLI.
class MockProtocolGen: ProtocolGenerating {
    var generateCalled = false
    var capturedTranscript: String?
    var capturedTitle: String?
    // swiftlint:disable:next discouraged_optional_boolean
    var capturedDiarized: Bool?
    var shouldThrow = false

    func generate(transcript: String, title: String, diarized: Bool) throws -> String {
        generateCalled = true
        capturedTranscript = transcript
        capturedTitle = title
        capturedDiarized = diarized
        if shouldThrow {
            throw NSError(
                domain: "MockProtocolGen",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey: "Mock protocol error"],
            )
        }
        return """
        # Meeting Protocol - \(title)
        **Date:** 2026-03-06

        ---

        ## Summary
        Test protocol generated by mock.
        """
    }
}

/// Mock transcription engine for pipeline tests.
@MainActor
class MockEngine: TranscribingEngine {
    var modelState: ModelState = .loaded
    var downloadProgress: Double = 1.0
    var transcriptionProgress: Double = 1.0
    var segmentsToReturn: [TimestampedSegment] = []
    var transcribeCallCount = 0
    var shouldThrow = false

    func loadModel() {
        modelState = .loaded
    }

    func transcribeSegments(audioPath _: URL) throws -> [TimestampedSegment] {
        transcribeCallCount += 1
        if shouldThrow {
            throw NSError(domain: "MockEngine", code: 1, userInfo: [NSLocalizedDescriptionKey: "Mock transcription error"])
        }
        return segmentsToReturn
    }
}

// MARK: - Meeting Simulator (for E2E tests)

/// Helpers for building and launching the meeting-simulator tool.
enum SimulatorHelper {
    /// Project root derived from the test file location.
    /// Tests/ → MeetingTranscriber/ → app/ → project root
    static let projectRoot: URL = .init(fileURLWithPath: #filePath)
        .deletingLastPathComponent() // Tests/
        .deletingLastPathComponent() // MeetingTranscriber/
        .deletingLastPathComponent() // app/
        .deletingLastPathComponent() // project root

    /// Path to the meeting-simulator SPM package.
    static let simulatorPackage = projectRoot.appendingPathComponent("tools/meeting-simulator")

    /// Path to the two-speaker German test fixture.
    static let fixtureAudio: URL = .init(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .appendingPathComponent("Fixtures/two_speakers_de.wav")

    /// Builds the meeting-simulator executable and returns the binary path.
    static func buildSimulator() throws -> URL {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/swift")
        process.arguments = ["build", "-c", "release"]
        process.currentDirectoryURL = simulatorPackage
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe
        try process.run()
        // Drain pipe before waitUntilExit to prevent deadlock if output exceeds pipe buffer
        let outputData = pipe.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            let output = String(data: outputData, encoding: .utf8) ?? ""
            throw NSError(
                domain: "SimulatorHelper",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey: "meeting-simulator build failed: \(output)"],
            )
        }
        return simulatorPackage.appendingPathComponent(".build/release/meeting-simulator")
    }

    /// Launches the meeting-simulator as a subprocess playing the given audio file.
    static func launchSimulator(binary: URL, audioPath: URL) throws -> Process {
        let process = Process()
        process.executableURL = binary
        process.arguments = [audioPath.path]
        try process.run()
        return process
    }
}

// MARK: - Test Audio Fixture

/// Create a minimal valid 16kHz Float32 mono WAV (0.5s silence).
/// Uses UUID in filename to avoid collisions across concurrent tests.
func createTestAudioFile(in dir: URL) throws -> URL {
    let audioPath = dir.appendingPathComponent("test_audio_\(UUID().uuidString).wav")
    var header = Data(count: 44)
    header[0] = 0x52; header[1] = 0x49; header[2] = 0x46; header[3] = 0x46 // RIFF
    let fileSize = UInt32(44 + 32000 - 8)
    header.replaceSubrange(4 ..< 8, with: withUnsafeBytes(of: fileSize.littleEndian) { Data($0) })
    header[8] = 0x57; header[9] = 0x41; header[10] = 0x56; header[11] = 0x45 // WAVE
    header[12] = 0x66; header[13] = 0x6D; header[14] = 0x74; header[15] = 0x20 // fmt
    header.replaceSubrange(16 ..< 20, with: withUnsafeBytes(of: UInt32(16).littleEndian) { Data($0) })
    header.replaceSubrange(20 ..< 22, with: withUnsafeBytes(of: UInt16(3).littleEndian) { Data($0) }) // Float
    header.replaceSubrange(22 ..< 24, with: withUnsafeBytes(of: UInt16(1).littleEndian) { Data($0) }) // mono
    header.replaceSubrange(24 ..< 28, with: withUnsafeBytes(of: UInt32(16000).littleEndian) { Data($0) }) // 16kHz
    header.replaceSubrange(28 ..< 32, with: withUnsafeBytes(of: UInt32(64000).littleEndian) { Data($0) }) // byte rate
    header.replaceSubrange(32 ..< 34, with: withUnsafeBytes(of: UInt16(4).littleEndian) { Data($0) }) // block align
    header.replaceSubrange(34 ..< 36, with: withUnsafeBytes(of: UInt16(32).littleEndian) { Data($0) }) // bits
    header[36] = 0x64; header[37] = 0x61; header[38] = 0x74; header[39] = 0x61 // data
    header.replaceSubrange(40 ..< 44, with: withUnsafeBytes(of: UInt32(32000).littleEndian) { Data($0) })
    var data = header
    data.append(Data(repeating: 0, count: 32000))
    try data.write(to: audioPath)
    return audioPath
}
